# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetCheckpoint = channel.unary_unary(
                '/agent.AgentControl/SetCheckpoint',
                request_serializer=agent__pb2.Position.SerializeToString,
                response_deserializer=agent__pb2.Empty.FromString,
                _registered_method=True)
        self.SetPath = channel.unary_unary(
                '/agent.AgentControl/SetPath',
                request_serializer=agent__pb2.Path.SerializeToString,
                response_deserializer=agent__pb2.Empty.FromString,
                _registered_method=True)
        self.ObservePosition = channel.unary_unary(
                '/agent.AgentControl/ObservePosition',
                request_serializer=agent__pb2.PositionObservation.SerializeToString,
                response_deserializer=agent__pb2.Empty.FromString,
                _registered_method=True)
        self.StreamPosition = channel.unary_stream(
                '/agent.AgentControl/StreamPosition',
                request_serializer=agent__pb2.Empty.SerializeToString,
                response_deserializer=agent__pb2.Position.FromString,
                _registered_method=True)
        self.StreamRays = channel.unary_stream(
                '/agent.AgentControl/StreamRays',
                request_serializer=agent__pb2.Empty.SerializeToString,
                response_deserializer=agent__pb2.RayBatch.FromString,
                _registered_method=True)


class AgentControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObservePosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRays(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCheckpoint,
                    request_deserializer=agent__pb2.Position.FromString,
                    response_serializer=agent__pb2.Empty.SerializeToString,
            ),
            'SetPath': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPath,
                    request_deserializer=agent__pb2.Path.FromString,
                    response_serializer=agent__pb2.Empty.SerializeToString,
            ),
            'ObservePosition': grpc.unary_unary_rpc_method_handler(
                    servicer.ObservePosition,
                    request_deserializer=agent__pb2.PositionObservation.FromString,
                    response_serializer=agent__pb2.Empty.SerializeToString,
            ),
            'StreamPosition': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPosition,
                    request_deserializer=agent__pb2.Empty.FromString,
                    response_serializer=agent__pb2.Position.SerializeToString,
            ),
            'StreamRays': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRays,
                    request_deserializer=agent__pb2.Empty.FromString,
                    response_serializer=agent__pb2.RayBatch.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.AgentControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.AgentControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentControl/SetCheckpoint',
            agent__pb2.Position.SerializeToString,
            agent__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentControl/SetPath',
            agent__pb2.Path.SerializeToString,
            agent__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObservePosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentControl/ObservePosition',
            agent__pb2.PositionObservation.SerializeToString,
            agent__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agent.AgentControl/StreamPosition',
            agent__pb2.Empty.SerializeToString,
            agent__pb2.Position.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRays(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agent.AgentControl/StreamRays',
            agent__pb2.Empty.SerializeToString,
            agent__pb2.RayBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
